# MANIPULATING TENSORS WITH TENSORFLOW

In [39]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.4.1


## 0. Tensors with `tf.constant`
tf.constant: creates a constant tensor from a tensor-like object

Once assigned, they can't be changed

In [ ]:
# creating a scalar
scalar = tf.constant(12)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
# creating a vector
vector = tf.constant([25,10,93])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 10, 93], dtype=int32)>

In [ ]:
# creating a matrix
matrix = tf.constant([[25,10],
                      [19,93]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 10],
       [19, 93]], dtype=int32)>

In [ ]:
# creating a tensor
tensor = tf.constant([[[25,10],
                      [19,93]],

                      [[11,40],
                       [20,10]],
                      
                      [[1,2],
                       [2,3]]])
tensor # that is, 3 matrices of 2x2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[25, 10],
        [19, 93]],

       [[11, 40],
        [20, 10]],

       [[ 1,  2],
        [ 2,  3]]], dtype=int32)>

#### Dimension of a tensor

scalar has a 0 dimension because the shape in the above output is zero

In [ ]:
print(f'scalar dim: {scalar.ndim}')
print(f'vector dim: {vector.ndim}')
print(f'matrix dim: {matrix.ndim}')
print(f'tensor dim: {tensor.ndim}')

scalar dim: 0
vector dim: 1
matrix dim: 2
tensor dim: 3


## 1. Tensors with `tf.Variable`

They can be changed using `.assign`

In [7]:
changeable_tensor = tf.Variable([10,7])
unchangeble_twnsor = tf.constant([10,7])
changeable_tensor,unchangeble_twnsor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [9]:
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

## 2. Creating Random Tensors - `tf.random.Generator`

Random tensors are tensors of some arbitrary size which contain random numbers.

In [15]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2,1))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2,1))
random_1, random_2

(<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[-0.7565803 ],
         [-0.06854702]],
 
        [[ 0.07595026],
         [-1.2573844 ]],
 
        [[-0.23193763],
         [-1.8107855 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[-0.7565803 ],
         [-0.06854702]],
 
        [[ 0.07595026],
         [-1.2573844 ]],
 
        [[-0.23193763],
         [-1.8107855 ]]], dtype=float32)>)

## 3. Shuffle the Order of a Tensor

`tf.random.shuffle`: shuffles the tensor along its first dimension.

If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [20]:
tf.random.shuffle(random_1, seed = 42)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.23193763],
        [-1.8107855 ]],

       [[ 0.07595026],
        [-1.2573844 ]],

       [[-0.7565803 ],
        [-0.06854702]]], dtype=float32)>

In [35]:
tf.random.set_seed(4)
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]],

       [[-0.23193763],
        [-1.8107855 ]]], dtype=float32)>

## 4. Tensors and Numpy Arrays

The main difference between them is that tensors can be run on GPU, so, it's much faster.

In [44]:
# tensor of ones
tf.ones([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [45]:
# all zeroes
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [47]:
tf.identity([2,2])

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [61]:
# turning numpy arrays into tensors
a = np.arange(0, 12)
A = tf.constant(a, shape=(2,3,2))
a, A

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 <tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])>)