# MANIPULATING TENSORS WITH TENSORFLOW!

In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.4.1


## 0. Tensors with `tf.constant`
tf.constant: creates a constant tensor from a tensor-like object

Once assigned, they can't be changed

In [2]:
# creating a scalar
scalar = tf.constant(12)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [3]:
# creating a vector
vector = tf.constant([25,10,93])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 10, 93], dtype=int32)>

In [4]:
# creating a matrix
matrix = tf.constant([[25,10],
                      [19,93]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 10],
       [19, 93]], dtype=int32)>

In [5]:
# creating a tensor
tensor = tf.constant([[[25,10],
                      [19,93]],

                      [[11,40],
                       [20,10]],
                      
                      [[1,2],
                       [2,3]]])
tensor # that is, 3 matrices of 2x2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[25, 10],
        [19, 93]],

       [[11, 40],
        [20, 10]],

       [[ 1,  2],
        [ 2,  3]]], dtype=int32)>

#### Dimension of a tensor

scalar has a 0 dimension because the shape in the above output is zero

In [6]:
print(f'scalar dim: {scalar.ndim}')
print(f'vector dim: {vector.ndim}')
print(f'matrix dim: {matrix.ndim}')
print(f'tensor dim: {tensor.ndim}')

scalar dim: 0
vector dim: 1
matrix dim: 2
tensor dim: 3


## 1. Tensors with `tf.Variable`

They can be changed using `.assign`

In [7]:
changeable_tensor = tf.Variable([10,7])
unchangeble_twnsor = tf.constant([10,7])
changeable_tensor,unchangeble_twnsor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

## 2. Creating Random Tensors - `tf.random.Generator`

Random tensors are tensors of some arbitrary size which contain random numbers.

In [9]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2,1))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2,1))
random_1, random_2

(<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[-0.7565803 ],
         [-0.06854702]],
 
        [[ 0.07595026],
         [-1.2573844 ]],
 
        [[-0.23193763],
         [-1.8107855 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[-0.7565803 ],
         [-0.06854702]],
 
        [[ 0.07595026],
         [-1.2573844 ]],
 
        [[-0.23193763],
         [-1.8107855 ]]], dtype=float32)>)

## 3. Shuffle the Order of a Tensor

`tf.random.shuffle`: shuffles the tensor along its first dimension.

If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [10]:
tf.random.shuffle(random_1, seed = 42)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.23193763],
        [-1.8107855 ]],

       [[ 0.07595026],
        [-1.2573844 ]],

       [[-0.7565803 ],
        [-0.06854702]]], dtype=float32)>

In [11]:
tf.random.set_seed(4)
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]],

       [[-0.23193763],
        [-1.8107855 ]]], dtype=float32)>

## 4. Tensors and Numpy Arrays

The main difference between them is that tensors can be run on GPU, so, it's much faster.

In [12]:
# tensor of ones
tf.ones([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [13]:
# all zeroes
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [14]:
tf.identity([2,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [15]:
# turning numpy arrays into tensors
a = np.arange(0, 12)
A = tf.constant(a, shape=(2,3,2))
a, A

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 <tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])>)

## 5. Getting Information from Tensors

- Shape: the length of each of the dimensions of a tensor [`tensor.shape`]
- Rank: the number of tensor dimensions. [`tensor.ndim`]
    - scalar -> rank 0
    - vector -> rank 1
    - matrix -> rank 2
    - tensor -> tank n
- Axis or Dimension: a particular dimension of a tensor [`tensor[0]`]
-Size: the total number of items in the tensor [`tf.size(tensor)`]

In [16]:
rank_4 = tf.random.normal(shape=[2,2,4,5])
rank_4

<tf.Tensor: shape=(2, 2, 4, 5), dtype=float32, numpy=
array([[[[ 0.05207799, -0.31717038, -1.0532024 ,  1.5985919 ,
           0.01665103],
         [-0.4303758 , -0.4309022 ,  1.9112922 ,  0.9449444 ,
          -0.16886725],
         [-2.1066759 ,  1.3980145 ,  0.44849458,  0.60391724,
          -1.1754872 ],
         [-0.74158764,  0.47670206, -0.7896117 , -0.95184433,
           0.5406662 ]],

        [[-0.7202453 , -0.818069  , -1.3891615 , -1.6312046 ,
           1.7408795 ],
         [-1.5092139 ,  1.5913574 ,  0.82941824,  1.4146508 ,
          -0.61505896],
         [-1.6049461 ,  0.5125865 , -2.6012802 , -0.38644642,
           1.0358859 ],
         [ 0.55974054,  0.17143811,  1.513643  , -1.1207025 ,
           0.27213812]]],


       [[[ 0.8913455 ,  1.0133594 , -0.30707034, -0.2589502 ,
           1.6198119 ],
         [ 0.24717619, -0.33695406, -0.45682883,  0.03019781,
          -1.9771404 ],
         [-1.559565  , -1.6705179 ,  0.85525334,  0.45735577,
           0.68701

In [17]:
rank_4.shape, rank_4.ndim, tf.size(rank_4).numpy()

(TensorShape([2, 2, 4, 5]), 4, 80)

## 6. Indexing Tensors

The indexing works just like in python lists.

In [18]:
# first 2 elements of each dimensions
rank_4[:2, :2, :2, :3]

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[ 0.05207799, -0.31717038, -1.0532024 ],
         [-0.4303758 , -0.4309022 ,  1.9112922 ]],

        [[-0.7202453 , -0.818069  , -1.3891615 ],
         [-1.5092139 ,  1.5913574 ,  0.82941824]]],


       [[[ 0.8913455 ,  1.0133594 , -0.30707034],
         [ 0.24717619, -0.33695406, -0.45682883]],

        [[ 0.25852808,  0.90809107,  0.76973355],
         [ 0.44313943, -0.8858351 , -0.2969878 ]]]], dtype=float32)>

In [19]:
# get the first elements from each dimension from each index except for the final one
rank_4[1:, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[ 0.8913455 ,  1.0133594 , -0.30707034, -0.2589502 ,
           1.6198119 ]]]], dtype=float32)>

In [20]:
rank_2 = tf.random.uniform(shape=[2,2])
rank_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.546034  , 0.7847378 ],
       [0.04293239, 0.5031413 ]], dtype=float32)>

In [21]:
# get the last item of each row
rank_2[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.7847378, 0.5031413], dtype=float32)>

In [22]:
# adding in extra dimension
rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.546034  ],
        [0.7847378 ]],

       [[0.04293239],
        [0.5031413 ]]], dtype=float32)>

In [23]:
rank_2[:, tf.newaxis, :]

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0.546034  , 0.7847378 ]],

       [[0.04293239, 0.5031413 ]]], dtype=float32)>

In [24]:
tf.expand_dims(rank_2, -1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.546034  ],
        [0.7847378 ]],

       [[0.04293239],
        [0.5031413 ]]], dtype=float32)>

## 7. Manipulating Tensors

### Basic Operations
+, -, *, /

In [25]:
tensor = tf.constant([[1,2],
                      [3,4]]) 
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [26]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [27]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [28]:
# using Tensorflow builtin functions
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [29]:
tf.math.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

## 8. Matrix Multipllication

In [30]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [31]:
# with python
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [32]:
X = tf.constant([[1,2,3],
                 [1,2,3]])
tf.matmul(X, tf.transpose(X))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 14],
       [14, 14]], dtype=int32)>

In [33]:
tf.tensordot(X, tf.transpose(X), axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 14],
       [14, 14]], dtype=int32)>

In [34]:
tf.matmul(X, tf.reshape(X,  shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 13],
       [13, 13]], dtype=int32)>

In [35]:
tf.reshape(X,  shape=(3,2)), tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 1],
        [2, 3]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2],
        [3, 3]], dtype=int32)>)

## 9. Changing Datatype of a Tensor

If I create a tensor containing floats inside, its type will be float. The same happens to integer.

In [36]:
tensor1 = tf.constant([2.1, 2.5, 2.6])
tensor2 = tf.constant([1, 5, 6])
tensor1.dtype, tensor2.dtype

(tf.float32, tf.int32)

In [37]:
# reduce precision: float32 to float16
tensor1 = tf.cast(tensor1, dtype = tf.float16)
tensor2 = tf.cast(tensor2, dtype = tf.int16)

tensor1.dtype, tensor2.dtype

(tf.float16, tf.int16)

## 10. Aggreagating Tensors

Aggreagating tensors = condensing them from multiple values down to a smaller amount of values.

In [39]:
# absolute values
## return int or float depending on the data type.
tensor = tf.constant([-1,1])
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [43]:
tensor = tf.constant(np.random.randint(0,100, size = 50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([80, 26, 87, 96, 35, 11, 82, 98, 44, 75, 79, 66, 38, 12, 35, 16,  2,
       24, 48, 51, 48, 19, 80, 34, 84, 35, 79, 43, 94, 89, 27, 19, 79, 78,
        6, 42, 76, 30, 68, 19, 34, 65, 85, 93, 33, 40, 61, 16, 72, 59])>

In [45]:
tf.size(tensor), tensor.shape, tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [47]:
# minimum
tf.reduce_min(tensor), np.min(tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>, 2)

In [48]:
# maximum
tf.reduce_max(tensor), np.max(tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=98>, 98)

In [50]:
# mean
tf.reduce_mean(tf.cast(tensor, dtype = tf.float32)), np.mean(tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=52.24>, 52.24)

We had to convert its type to float because tf.reduce_mean returns the same type. So, it was returning the mean as integer.

In [51]:
# sum
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2612>

In [59]:
# standard deviation
tf.math.reduce_std(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.78745>

In [66]:
# variance way 1
import tensorflow_probability as tfp
tfp.stats.variance(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=772.1424>

In [68]:
# variance way 2
tf.math.reduce_variance(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=772.1424>

## 11. Find the positional maxumim and minimum

Usefull in NN probability output.
At which index of the tensor does the maximum/minimum value occur.

In [70]:
tf.random.set_seed(42)
T = tf.random.uniform(shape=[50])
T

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [71]:
# finding the positional maximum
tf.argmax(T)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [73]:
# getting the argmax value
T[tf.argmax(T)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [75]:
# finding the positional minimum
tf.argmin(T)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [76]:
T = tf.constant([[1,2],
                 [3,4]])
tf.argmax(T)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

## Squeezing a tensor

It's just removing 1 dimensions 

In [79]:
T = tf.constant(tf.random.uniform(shape=[20]), shape=[1,1,1,1,20])
T

<tf.Tensor: shape=(1, 1, 1, 1, 20), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506]]]]],
      dtype=float32)>

In [81]:
tf.squeeze(T), tf.squeeze(T).shape

(<tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506],
       dtype=float32)>, TensorShape([20]))

## 12. One-hot Encoding Tensors

In [85]:
indices = [0,1,2, 3]
depth = 4

tf.one_hot(indices, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [86]:
tf.one_hot(indices, depth, on_value='yes', off_value='no')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

### 13. More Math

In [98]:
T = tf.constant([2,2,3,4 ], dtype= tf.float32)

In [104]:
# natural exponential
tf.exp(T)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 7.389056,  7.389056, 20.085537, 54.59815 ], dtype=float32)>

In [99]:
# natural log
tf.math.log(T)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.6931472, 0.6931472, 1.0986123, 1.3862944], dtype=float32)>

In [100]:
# squared root
tf.math.sqrt(T)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.4142135, 1.4142135, 1.7320508, 2.       ], dtype=float32)>

In [103]:
# power
tf.math.pow(T, [2,2,2,2])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 4.,  4.,  9., 16.], dtype=float32)>

In [105]:
# square
tf.square(T)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 4.,  4.,  9., 16.], dtype=float32)>

When creating a tensor with numpy array, the default dtype is going to be float64. If we do it from a list, the default type is going to be float32

In [106]:
numpy_T = tf.constant(np.array([2.,3.]))
tensor_T = tf.constant([2.,3.])

numpy_T.dtype, tensor_T.dtype

(tf.float64, tf.float32)

## 14. Finding access to GPUs

In [109]:
# list devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]